apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rolap
resources:
  - ../base/rolap
patchesStrategicMerge:
  - rolap/dwh-log/kafka-patch.yaml
patchesJson6902:
- target:
    group: kafka.strimzi.io
    version: v1beta1
    kind: Kafka
    name: dwh-log
  path: rolap/dwh-log/kafka-hostnames.yaml

